services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pcm_sql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Chi@2005!
    ports:
      - "1433:1433"
    volumes:
      - pcm_sql_data:/var/opt/mssql

  api:
    build:
      context: ./PcmBackend
      dockerfile: Dockerfile
    container_name: pcm_web_api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Connection String trỏ vào service 'db' thay vì địa chỉ máy cá nhân
      - ConnectionStrings__DefaultConnection=Server=db;Database=PcmDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;

volumes:
  pcm_sql_data: